diplom/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from django.contrib.auth import views as auth_views


app_name = 'diplom'
urlpatterns = [
    url(r'^logout/$', auth_views.logout, {'next_page': 'diplom:login'},  name='logout'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},  name='login'),
    # ex: /diplom/home/
    url(r'^home/$', views.list_projects, name='projects'),
    url(r'^home/add/$', login_required(views.TpCreate.as_view()), name='tp-add'),
    url(r'^home/close/(?P<tp_id>[0-9]+)/$', views.close_project, name='tp-close'),

    url(r'^home/(?P<tp_id>[0-9]+)/$', views.list_testsuits, name='list_testsuits'),
    url(r'^home/(?P<tp_id>[0-9]+)/testsuit/add/$',login_required(views.TsCreate.as_view()), name='ts-add'),

    url(r'^home/(?P<tp_id>[0-9]+)/(?P<ts_id>[0-9]+)/testcase/$',login_required( views.TcList.as_view()), name='tc-list'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<ts_id>[0-9]+)/detail/(?P<pk>[0-9]+)/$', login_required(views.TcDetail.as_view()), name='tc-detail'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<ts_id>[0-9]+)/testcase/add/$',login_required( views.TcCreate.as_view()), name='tc-add'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<ts_id>[0-9]+)/update/(?P<pk>[0-9]+)/$', login_required(views.TcUpdate.as_view()), name='tc-update'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<ts_id>[0-9]+)/delete/(?P<pk>[0-9]+)/$', login_required(views.TcDelete.as_view()), name='tc-delete'),
    url(r'^home/(?P<tp_id>[0-9]+)/testcase/search/$',login_required( views.TcListSearch.as_view()), name='tc-search'),

    url(r'^home/(?P<tp_id>[0-9]+)/testruns/$', views.list_testruns, name='list-testruns'),
    url(r'^home/(?P<tp_id>[0-9]+)/testrun/add/$',login_required( views.TrCreate.as_view()), name='tr-add'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<tr_id>[0-9]+)/testrun/$',login_required( views.TrDetailList.as_view()), name='tr-detail-list'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<tr_id>[0-9]+)/result/(?P<pk>[0-9]+)/$',login_required( views.TrrDetail.as_view()), name='trr-detail'),
    url(r'^home/(?P<tp_id>[0-9]+)/(?P<tr_id>[0-9]+)/(?P<tc_id>[0-9]+)/result/add/$',login_required( views.TrrCreate.as_view()), name='trr-add'),
]

tms/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^diplom/', include('diplom.urls')),

]

diplom/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class StatusTestRun (models.Model):
    name = models.CharField(max_length=90)

    def __str__(self):
        return self.name

class ProjectStatus (models.Model):
    name = models.CharField(max_length=90)

    def __str__(self):
        return self.name


class Priority(models.Model):
    name = models.CharField(max_length=90)

    def __str__(self):
        return self.name


class TestProject(models.Model):
    status = models.ForeignKey(ProjectStatus)
    user = models.ForeignKey(User)
    name = models.CharField(max_length=90)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('diplom:projects')


class TestSuit (models.Model):
    name = models.CharField(max_length=90)
    description = models.TextField(blank = True)
    project = models.ForeignKey(TestProject)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('diplom:list_testsuits', kwargs={'tp_id':self.project.pk})#формиров ссылки при изменении

class TestCase(models.Model):
    testSuit = models.ForeignKey(TestSuit)
    priority = models.ForeignKey(Priority)
    title = models.CharField(max_length=255)
    estimate = models.CharField(max_length=255)
    precondition = models.TextField(blank = True)
    steps = models.TextField()
    expected_result = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('diplom:tc-list', kwargs={'tp_id':self.testSuit.project.pk, 'ts_id':self.testSuit.pk})


class TestRun(models.Model):
     testProject = models.ForeignKey(TestProject)
     name = models.CharField(max_length=90)
     description = models.TextField(blank = True)
     testcases = models.ManyToManyField(TestCase, through='TestRunTestCase', through_fields=('testRun', 'testCase'),)

     def __str__(self):
        return self.name

     def get_absolute_url(self):
        return reverse('diplom:list-testruns', kwargs={'tp_id':self.testProject.pk})


class TestRunTestCase(models.Model):
    testRun = models.ForeignKey(TestRun, on_delete=models.CASCADE)# парам кот указыв все записи буд уд
    testCase = models.ForeignKey(TestCase, on_delete=models.CASCADE)

    class Meta:
        auto_created = True#одновременн изм и Test R и TestCase

class TestRunResult(models.Model):
   testrunTestcase = models.OneToOneField(TestRunTestCase, on_delete=models.CASCADE, primary_key=True,)
   user = models.ForeignKey(User)
   status = models.ForeignKey(StatusTestRun)
   comment = models.CharField(max_length=255,blank = True)
   trrDate = models.DateTimeField()

   def get_absolute_url(self):
        return reverse('diplom:trr-detail', kwargs={'tp_id':self.testrunTestcase.testRun.testProject.pk,#записів ключи
                       'tr_id':self.testrunTestcase.testRun.pk,
                       'pk':self.testrunTestcase.testCase.pk})

   class Meta:
        auto_created = True

   def __str__(self):
        return self.comment

diplom/forms.py
from django import forms


class TestCaseForm(forms.Form):
   title = forms.CharField()
   steps = forms.CharField(widget=forms.Textarea)

diplom/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import  ListView, DetailView
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from .models import *
from .forms import *
from django.db.models import Q
from functools import reduce
import operator
from django.utils import timezone


@login_required
def list_projects(request):
    test_projects = TestProject.objects.all()
    context = {
        'test_projects':test_projects,
    }
    return render(request,"diplom/home.html",context)

class TpCreate(CreateView):
    model = TestProject
    fields = ['name']
    template_name = 'diplom/add.html'

    def form_valid(self, form):
        form.instance.status = ProjectStatus.objects.get(name="Open")#один обьект у модели testProject id кот передается через url
        form.instance.user = self.request.user
        return super(TpCreate, self).form_valid(form)


@login_required
def close_project(request,tp_id):
    project = TestProject.objects.get(pk=tp_id)
    context = {
        'tp_id':tp_id,
        'project':project,
    }
    if request.method=='POST':
        project.status = ProjectStatus.objects.get(name='Closed')
        project.save()
        return redirect('diplom:projects')
    else:
        return render(request,"diplom/close.html", context)


@login_required
def list_testsuits(request,tp_id):
    test_suites = TestSuit.objects.filter(project=tp_id)
    project = TestProject.objects.get(pk=tp_id)
    context = {
        'test_suites':test_suites,
        'tp_id':tp_id,
        'project':project
    }
    return render(request,"diplom/test_suite/list.html",context)

class TsCreate(CreateView):
    model = TestSuit
    fields = ['name', 'description']
    template_name = 'diplom/test_suite/add.html'

    #если нам нужно,чтобы подтягивалось какое то поле не через UI
    def form_valid(self, form):
        form.instance.project = TestProject.objects.get(pk=self.kwargs['tp_id'])#один обьект у модели testProject id кот передается через url
        return super(TsCreate, self).form_valid(form)

    #выбираем те данные котроые будем передавать в качестве контекста шаблону(конечн результат будет формир)
    def get_context_data(self, **kwargs):
        context = super(TsCreate, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        return context


class TcList(ListView):
    template_name ='diplom/testcase/list.html'
    model=TestCase
    #context_object_name = 'latest_title_list'

    def get_context_data(self, **kwargs):
        context = super(TcList, self).get_context_data(**kwargs)
        context['testSuit'] = get_object_or_404(TestSuit,pk= self.kwargs['ts_id'])#TestSuit.objects.filter(pk = self.kwargs['ts_id'])
        context['project']= get_object_or_404(TestProject,pk= self.kwargs['tp_id'])
        context['test_cases']=TestCase.objects.filter( testSuit = self.kwargs['ts_id'])
        return context

    #def get_queryset(self):
    #    return TestCase.objects.filter( testSuit = self.kwargs['ts_id'])

class TcCreate(CreateView):
    model = TestCase
    fields = ['title', 'priority', 'estimate', 'precondition', 'steps', 'expected_result' ]
    template_name = 'diplom/testcase/add.html'

    def form_valid(self, form):
        form.instance.testSuit = TestSuit.objects.get(pk=self.kwargs['ts_id'])
        return super(TcCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TcCreate, self).get_context_data(**kwargs)
        context['project'] = TestProject.objects.get(pk=self.kwargs['tp_id'])
        return context


class TcUpdate(UpdateView):
    template_name = 'diplom/testcase/edit.html'
    model = TestCase
    fields = ['title', 'priority', 'estimate', 'precondition', 'steps', 'expected_result' ]

    def get_context_data(self, **kwargs):
        context = super(TcUpdate, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        return context


class TcDelete(DeleteView):
     model = TestCase
     template_name = 'diplom/testcase/delete.html'

     def get_success_url(self):
         return reverse_lazy('diplom:tc-list', kwargs={'tp_id':self.kwargs['tp_id'], 'ts_id':self.kwargs['ts_id']})

     def get_context_data(self, **kwargs):
        context = super(TcDelete, self).get_context_data(**kwargs)
        context['testSuit'] = self.kwargs['ts_id']
        context['project']=  self.kwargs['tp_id']
        context['test_case']=self.kwargs['pk']
        return context

class TcDetail(DetailView):
    model = TestCase
    template_name = 'diplom/testcase/detail.html'

    def get_context_data(self, **kwargs):
        context = super(TcDetail, self).get_context_data(**kwargs)
        context['testSuit'] = self.kwargs['ts_id']
        context['project']=  self.kwargs['tp_id']
        context['test_case']=self.kwargs['pk']
        return context


@login_required
def list_testruns(request,tp_id):
    test_runs = TestRun.objects.filter(testProject=tp_id).order_by("-name")
    project = TestProject.objects.get(pk = tp_id)
    context = {
        'test_runs':test_runs,
        'tp_id':tp_id,
        'project':project
    }
    return render(request,"diplom/testrun/list.html",context)


class TcListSearch(ListView):
    template_name ='diplom/testcase/search-list.html'
    context_object_name = 'test_cases'
    def get_queryset(self):
        result = TestCase.objects.filter(testSuit__project__id = self.kwargs['tp_id'])
        print(len(result))
        query = self.request.GET.get('q')

        if query:
            query_list = query.split()
            print(query_list)
            result = result.filter(
                reduce(operator.and_,
                    (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                    (Q(steps__icontains=q) for q in query_list))
            )
        return result

    def get_context_data(self, **kwargs):
        context = super(TcListSearch, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        context['search_word'] = self.request.GET.get('q')
        return context


class TrCreate(CreateView):
    model = TestRun
    fields = ['name', 'description', 'testcases' ]
    template_name = 'diplom/testrun/add.html'

    def form_valid(self, form):
        form.instance.testProject = TestProject.objects.get(pk=self.kwargs['tp_id'])
        return super(TrCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TrCreate, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        return context


class TrDetailList(ListView):
    template_name ='diplom/testrun/tr-detail-list.html'
    context_object_name = 'testrun_testcase'
    #model=TestRun
    def get_queryset(self):
        result = TestRunTestCase.objects.filter(testRun = self.kwargs['tr_id'])
        return result
        #return result.testcases.all()

    def get_context_data(self, **kwargs):
        context = super(TrDetailList, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        context['tr_id'] = self.kwargs['tr_id']
        context['testRun'] = TestRun.objects.get(pk = self.kwargs['tr_id'])
        return context


class TrrCreate(CreateView):
    model = TestRunResult
    fields = ['status', 'comment' ]
    template_name = 'diplom/testrun/result-add.html'

    def form_valid(self, form):
        form.instance.trrDate = timezone.now()
        form.instance.testrunTestcase = TestRunTestCase.objects.get(testRun=self.kwargs['tr_id'], testCase=self.kwargs['tc_id'])
        form.instance.user = self.request.user
        return super(TrrCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TrrCreate, self).get_context_data(**kwargs)
        context['tp_id'] = self.kwargs['tp_id']
        return context


class TrrDetail(DetailView):
    model = TestCase
    template_name = 'diplom/testrun/detail.html'

    def get_context_data(self, **kwargs):
        context = super(TrrDetail, self).get_context_data(**kwargs)
        context['tr_id'] = self.kwargs['tr_id']
        context['tp_id']=  self.kwargs['tp_id']
        context['tc_id']=self.kwargs['pk']
        context['project']=TestProject.objects.get(pk=context['tp_id'])
        context['testRun']=TestRun.objects.get(pk=context['tr_id'])
        try:
            context['run_result'] = TestRunResult.objects.get(
                testrunTestcase=TestRunTestCase.objects.get(testRun=context['tr_id'],
                                                            testCase= context['tc_id']))
        except TestRunResult.DoesNotExist:
            context['run_result'] = None
        return context

diplom/templates/diplom/add.html
{% extends "diplom/base.html" %}
{% load humanize %}
{% block project-name %} Projects{% endblock %}

        
{% block content %}
        <h3>Add Test Project</h3>
        <form method="post" action=".">
            {% csrf_token %}
        {{ form.as_p}}
         <input type ="submit" value="Save"/>
         </form>
{% endblock %}

diplom/templates/diplom/base-nav.html
{% extends "diplom/base.html" %}
{% load humanize %}

{% block nav %}
<ul class="nav nav-tabs">
    <li class="{% block tab1-active %} {% endblock %}">
        <a href=" {% block ts_url %} {% endblock %} ">Test Suites</a>
    </li>
    <li class="{% block tab2-active %} {% endblock %}">
        <a href=" {% block tr_url %} {% endblock %} ">Test Runs</a>
    </li>
</ul>
{% endblock %}

diplom/templates/diplom/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <title>Test case managment system</title>
    <meta charset="UTF-8">
    <meta name="description" content="Test Managment system">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700|Merriweather:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <div class="container">
        <header>
            <a href="{% url 'diplom:projects' %}"> <img src="{% static 'img/logo.png' %}" alt="TMS" class="logo"/></a>
            <div class="welcome">
                {% if request.user.is_authenticated %}
                    <p>Hello {{request.user.username|title }},you last logged in at  {{request.user.last_login}} <a href="{% url 'diplom:logout'%}" class="btn btn-primary">Logout</a></p>
                {% else %}
                    <p>Welcome guest! <a href="{% url 'diplom:login'%}">Login</a></p>
                {% endif %}
            </div>
        </header>
      <div class="well well-sm">  <h4>{% block project-name %}{% endblock %}</h4> </div>
   {% block nav %}{% endblock %}
        <main>
            {% block content %}{% endblock %}
        </main>


     </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

diplom/templates/diplom/close.html
{% extends "diplom/base-nav.html" %}
{% load humanize %}

{% block project-name %}{{project.name}} {% endblock %}
{% block ts_url %} {% url 'diplom:list_testsuits' project.id %} {% endblock %}
{% block tr_url %}{% url 'diplom:list-testruns'  project.id %} {% endblock %}
{% block tab1-active %}active {% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p><br>Are you sure you want to close "{{ project }}"?</p>
    <input type="submit" class="btn btn-xs  btn-danger" value="Confirm" />

</form>
  {% endblock %}

diplom/templates/diplom/home.html
{% extends "diplom/base.html" %}
{% load humanize %}
{% block project-name %} Projects{% endblock %}
{% block content %}
<div class="row">
  <div class="col-sm-4"> <h4>Open project(s)</h4></div>
  <div class="col-sm-8" style="text-align:right;"> <a  class="btn btn-md  btn-primary" href ="{% url 'diplom:tp-add'  %} ">Add Test Project</a></div>
</div>
    <hr>
    {% for test_project in test_projects %}
        {% if test_project.status.name == "Open" %}

    <div class="row">
  <div class="col-sm-4"><h5><a href="{% url 'diplom:list_testsuits' test_project.id %}"> {{test_project.name}}</a></h5>
            <a class="link" href="{% url 'diplom:list-testruns' test_project.id%}">Test Runs</a> |
            <a href="{% url 'diplom:list_testsuits' test_project.id %}"> Test Suites</a> |</div>

  <div class="col-sm-8" style="text-align:right;">
      <a href="{% url 'diplom:tp-close' test_project.id %}" class="btn btn-xs  btn-danger">Close Project</a></div>
</div>
            <hr>
        {% endif %}
    {% endfor%}
    <h4>Completed project</h4>
    {% for test_project in test_projects %}
        {% if test_project.status.name == "Closed" %}
    <h5><a href="{% url 'diplom:list_testsuits' test_project.id %}" style="font-style:italic;"> {{test_project.name}}</a></h5>

        {% endif %}
    {% endfor %}
{% endblock %}